### ISSUE TITLE
Library update error on Kodi 15.0 Isengard

### ISSUE THREAD

**Issue by beelzetron** [Jalle19/xbmc-video-server#226]
Internal server error when launching library update on Kodi 15.0 alpha2, the error message is:
```
exception 'CHttpException' with message 'Exception caught while calling XBMC API: A valid response status line was not found in the provided string (0)' in /var/www/html/xbmc/src/protected/components/XBMC.php:169

Stack trace:

#0 /var/www/html/xbmc/src/protected/components/XBMC.php(128): XBMC->handleRequestException(Object(SimpleJsonRpcClient\Exception\ClientException), Object(SimpleJsonRpcClient\Request\Notification))

#1 /var/www/html/xbmc/src/protected/controllers/BackendController.php(92): XBMC->sendNotification('VideoLibrary.Sc...')

#2 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(49): BackendController->actionUpdateLibrary()

#3 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)

#4 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CInlineAction))

#5 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()

#6 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(130): CFilter->filter(Object(CFilterChain))

#7 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()

#8 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/CController.php(1145): CFilter->filter(Object(CFilterChain))

#9 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))

#10 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))

#11 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilter.php(40): CFilterChain->run()

#12 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(130): CFilter->filter(Object(CFilterChain))

#13 /var/www/html/xbmc/src/protected/controllers/base/Controller.php(78): CFilterChain->run()

#14 /var/www/html/xbmc/src/protected/controllers/BackendController.php(49): Controller->filterCheckConfiguration(Object(CFilterChain))

#15 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): BackendController->filterCheckConfiguration(Object(CFilterChain))

#16 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))

#17 /var/www/html/xbmc/src/protected/controllers/base/Controller.php(61): CFilterChain->run()

#18 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): Controller->filterRequireLogin(Object(CFilterChain))

#19 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))

#20 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()

#21 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)

#22 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): CController->run('updateLibrary')

#23 /var/www/html/xbmc/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('backend/updateL...')

#24 /var/www/html/xbmc/vendor/yiisoft/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()

#25 /var/www/html/xbmc/src/index.php(17): CApplication->run()

#26 {main}
```

**Comment by Jalle19** [comment]
That's strange, when I tested this I just got a timeout instead. I've created a bug report for that: http://trac.kodi.tv/ticket/15922, until that is solved I can't replicate your issue completely.

**Comment by beelzetron** [comment]
Thank you!
