### ISSUE TITLE
/tmp not in open_basedir path(s)

### ISSUE THREAD

**Issue by Fogelholk** [Jalle19/xbmc-video-server#276]
Hi,
While trying to generate thumbnails xbmc-video-server fails because I have open_basedir activated in PHP.

I have set `upload_tmp_dir` to `/www/tmp` in my php.ini.

Error message below:
```
tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/www/tmp:/www/mydomain.com/public_html) (/www/mydomain.com/public_html/xbmc-video-server/src/protected/models/thumbnail/Thumbnail.php:111)

Stack trace:

#0 unknown(0): ThumbnailController->actionGenerate()

#1 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/actions/CAction.php(108): ReflectionMethod->invokeArgs()

#2 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/actions/CInlineAction.php(47): CInlineAction->runWithParamsInternal()

#3 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(308): CInlineAction->runWithParams()

#4 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(133): ThumbnailController->runAction()

#5 /www/mydomain.com/public_html/xbmc-video-server/src/protected/controllers/base/Controller.php(65): CFilterChain->run()

#6 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CInlineFilter.php(58): ThumbnailController->filterReleaseSessionLock()

#7 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/filters/CFilterChain.php(130): CInlineFilter->filter()

#8 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(291): CFilterChain->run()

#9 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CController.php(265): ThumbnailController->runActionWithFilters()

#10 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CWebApplication.php(282): ThumbnailController->run()

#11 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/web/CWebApplication.php(141): CWebApplication->runController()

#12 /www/mydomain.com/public_html/xbmc-video-server/vendor/yiisoft/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()

#13 /www/mydomain.com/public_html/xbmc-video-server/src/index.php(21): CWebApplication->run()

REQUEST_URI=/xbmc-video-server/src/thumbnail/generate?path=image%3A%2F%2Fhttp%253a%252f%252fthetvdb.com%252fbanners%252fposters%252f275274-6.jpg%2F&size=160
```

**Comment by Jalle19** [comment]
Can you try https://github.com/Jalle19/xbmc-video-server/commit/dcde662014f0d8dab2adf868815ec4de1a7b9844 ? Just run `git checkout tempdir`.

**Comment by Fogelholk** [comment]
Seems to be working! No error-messages and thumbnails are downloaded and generated :)

**Comment by Jalle19** [comment]
Good, I'll merge that to master then, after that you can run `git checkout master` once, then it's business as usual.

**Comment by Fogelholk** [comment]
Awesome! Thanks for the quick help and clear instructions :)
